export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_INIT = 'REGISTER_USER_INIT';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_INIT = 'LOGIN_USER_INIT';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_INIT = 'UPDATE_USER_INIT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_RECIPE_INIT = 'CREATE_RECIPE_INIT';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR';

export const GET_RECIPES_INIT = 'GET_RECIPES_INIT';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';

export const SET_EDIT_RECIPE = 'SET_EDIT_RECIPE';

export const DELETE_RECIPE_INIT = 'DELETE_RECIPE_INIT';

export const EDIT_RECIPE_INIT = 'EDIT_RECIPE_INIT';
export const EDIT_RECIPE_SUCCESS = 'EDIT_RECIPE_SUCCESS';
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';
